import Dashboard from '../Dashboard';
import { Product } from '@shared/schema';

export default function DashboardExample() {
  // todo: remove mock functionality
  const mockProducts: Product[] = [
    {
      id: '1',
      model: '1315',
      family: 'Embalagem',
      type: 'Boca Estreita',
      product: 'GARRAFÃO',
      productCode: 'GRF-1315',
      nominalCapacity: '15L',
      totalCapacity: '17.8L',
      rawMaterial: 'PEAD',
      colors: 'Branco, Azul',
      weight: '700g',
      weightWithAccessories: null,
      dimensions: '{"height": 332, "width": 284, "depth": 230}',
      closingSystem: 'Tampa de Rosca',
      sealingType: 'PEAD',
      handlingSystem: 'Pegas laterais',
      certifications: '["ADR 3H1/Y1,9/150"]',
      markings: '["Datador", "Símbolo SIE", "Capacidade Nominal"]',
      foodContact: true,
      packaging: '{"unitsPerPallet": 105, "unitsPerTruck": 3360}',
      specialFeatures: '["Empilhável", "Reciclável", "Reutilizável"]',
      createdAt: new Date('2024-09-01'),
      updatedAt: new Date('2024-09-01'),
      notes: null,
      isActive: true,
    },
    {
      id: '2',
      model: '1312',
      family: 'Embalagem',
      type: 'Boca Estreita',
      product: 'GARRAFÃO',
      productCode: 'GRF-1312',
      nominalCapacity: '5L',
      totalCapacity: '5.4L',
      rawMaterial: 'PEAD',
      colors: 'Incolor, Branco, Azul',
      weight: '220g',
      weightWithAccessories: null,
      dimensions: '{"height": 247, "width": 195, "depth": 145}',
      closingSystem: 'Tampa de Rosca',
      sealingType: 'PEAD',
      handlingSystem: 'Pegas laterais',
      certifications: '["ADR 3H1/Y1,4"]',
      markings: '["Datador", "Símbolo SIE"]',
      foodContact: true,
      packaging: '{"unitsPerPallet": 220, "unitsPerTruck": 7040}',
      specialFeatures: '["Empilhável", "Reciclável"]',
      createdAt: new Date('2024-08-15'),
      updatedAt: new Date('2024-08-15'),
      notes: null,
      isActive: true,
    },
    {
      id: '3',
      model: '1320',
      family: 'Embalagem', 
      type: 'Boca Estreita',
      product: 'GARRAFÃO',
      productCode: 'GRF-1320',
      nominalCapacity: '20L',
      totalCapacity: '21.7L',
      rawMaterial: 'PEAD',
      colors: 'Incolor, Branco, Azul, Amarelo, Vermelho, Cinzento',
      weight: '800g',
      weightWithAccessories: null,
      dimensions: '{"height": 395, "width": 284, "depth": 230}',
      closingSystem: 'Tampa de Rosca',
      sealingType: 'PEAD',
      handlingSystem: 'Pegas laterais',
      certifications: '["ADR 3H1/Y1,9/150"]',
      markings: '["Datador", "Símbolo SIE", "Capacidade Nominal"]',
      foodContact: true,
      packaging: '{"unitsPerPallet": 90, "unitsPerTruck": 2880}',
      specialFeatures: '["Empilhável", "Reciclável", "Reutilizável"]',
      createdAt: new Date('2024-09-15'),
      updatedAt: new Date('2024-09-15'),
      notes: 'Updated version with improved sealing',
      isActive: true,
    },
  ];

  return <Dashboard initialProducts={mockProducts} />;
}